/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse360;

import java.sql.*;
import javax.swing.*;
import cse360.sqliteConnection;
import cse360.User;

/**
 *
 * @author Jefferson
 */
public class PatientUI extends javax.swing.JFrame {

    ResultSet re = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form NewJFrame
     */
    public PatientUI() {
        initComponents();
        try{
            int mCount = 0;
            String recieve = User.getUsername();
            String sql = "SELECT Recieve FROM Messages";
            Connection conn = sqliteConnection.dbConnector();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next())
            {
                String check = rs.getString("Recieve");
                if(check.equals(recieve))
                {
                    mCount++;
                }
            }
            conn.close();
            newMessagesInfoD.setText("There are "+mCount+" messages");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainSeverity = new javax.swing.ButtonGroup();
        TirednessSeverity = new javax.swing.ButtonGroup();
        NauseaSeverity = new javax.swing.ButtonGroup();
        DepressionSeverity = new javax.swing.ButtonGroup();
        AnxietySeverity = new javax.swing.ButtonGroup();
        DrowsinessSeverity = new javax.swing.ButtonGroup();
        AppetiteSeverity = new javax.swing.ButtonGroup();
        WellbeingSeverity = new javax.swing.ButtonGroup();
        BreathSeverity = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        databaseP = new javax.swing.JButton();
        logOutP = new javax.swing.JButton();
        emergencyP = new javax.swing.JButton();
        painAndSymptoms = new javax.swing.JPanel();
        symptoms = new javax.swing.JPanel();
        symptomsLabel = new javax.swing.JLabel();
        severity = new javax.swing.JPanel();
        severityLabel = new javax.swing.JLabel();
        pain = new javax.swing.JLabel();
        tiredness = new javax.swing.JLabel();
        nausea = new javax.swing.JLabel();
        depression = new javax.swing.JLabel();
        anxiety = new javax.swing.JLabel();
        drowsiness = new javax.swing.JLabel();
        appetite = new javax.swing.JLabel();
        wellbeing = new javax.swing.JLabel();
        breath = new javax.swing.JLabel();
        painInfo = new javax.swing.JButton();
        tirednessInfo = new javax.swing.JButton();
        nauseaInfo = new javax.swing.JButton();
        depressionInfo = new javax.swing.JButton();
        anxietyInfo = new javax.swing.JButton();
        drowsinessInfo = new javax.swing.JButton();
        appetiteInfo = new javax.swing.JButton();
        wellbeingInfo = new javax.swing.JButton();
        breathInfo = new javax.swing.JButton();
        PainSymptomBox = new javax.swing.JComboBox();
        TirednessSymptomBox = new javax.swing.JComboBox();
        NauseaSymptomBox = new javax.swing.JComboBox();
        DepressionSymptomBox = new javax.swing.JComboBox();
        AnxietySymptomBox = new javax.swing.JComboBox();
        DrowsinessSymptomBox = new javax.swing.JComboBox();
        AppetiteSymptomBox = new javax.swing.JComboBox();
        WellbeingSymptomBox = new javax.swing.JComboBox();
        ShortBreathSymptomBox = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        messagesPanelD = new javax.swing.JPanel();
        messagesButtonD = new javax.swing.JButton();
        newMessagesInfoD = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        databaseP.setText("View Medical Record");
        databaseP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databasePActionPerformed(evt);
            }
        });

        logOutP.setText("Log Out");
        logOutP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutPActionPerformed(evt);
            }
        });

        emergencyP.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        emergencyP.setText("Emergency");
        emergencyP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyPActionPerformed(evt);
            }
        });

        painAndSymptoms.setBackground(new java.awt.Color(255, 255, 255));

        symptoms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        symptomsLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        symptomsLabel.setText("Symptoms");

        javax.swing.GroupLayout symptomsLayout = new javax.swing.GroupLayout(symptoms);
        symptoms.setLayout(symptomsLayout);
        symptomsLayout.setHorizontalGroup(
            symptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symptomsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(symptomsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        symptomsLayout.setVerticalGroup(
            symptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, symptomsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(symptomsLabel)
                .addContainerGap())
        );

        severity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        severityLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        severityLabel.setText("Severity");

        javax.swing.GroupLayout severityLayout = new javax.swing.GroupLayout(severity);
        severity.setLayout(severityLayout);
        severityLayout.setHorizontalGroup(
            severityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(severityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(severityLabel)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        severityLayout.setVerticalGroup(
            severityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, severityLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(severityLabel)
                .addContainerGap())
        );

        pain.setText("Pain");

        tiredness.setText("Tiredness");

        nausea.setText("Nausea");

        depression.setText("Depression");

        anxiety.setText("Anxiety");

        drowsiness.setText("Drowsiness");

        appetite.setText("Appetite");

        wellbeing.setText("Wellbeing");

        breath.setText("Shortness of Breath");

        painInfo.setText("?");

        tirednessInfo.setText("?");

        nauseaInfo.setText("?");

        depressionInfo.setText("?");

        anxietyInfo.setText("?");

        drowsinessInfo.setText("?");

        appetiteInfo.setText("?");

        wellbeingInfo.setText("?");
        wellbeingInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wellbeingInfoActionPerformed(evt);
            }
        });

        breathInfo.setText("?");

        PainSymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        PainSymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PainSymptomBoxActionPerformed(evt);
            }
        });

        TirednessSymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        TirednessSymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TirednessSymptomBoxActionPerformed(evt);
            }
        });

        NauseaSymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        NauseaSymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NauseaSymptomBoxActionPerformed(evt);
            }
        });

        DepressionSymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        DepressionSymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepressionSymptomBoxActionPerformed(evt);
            }
        });

        AnxietySymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        AnxietySymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnxietySymptomBoxActionPerformed(evt);
            }
        });

        DrowsinessSymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        DrowsinessSymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrowsinessSymptomBoxActionPerformed(evt);
            }
        });

        AppetiteSymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        AppetiteSymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppetiteSymptomBoxActionPerformed(evt);
            }
        });

        WellbeingSymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        WellbeingSymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WellbeingSymptomBoxActionPerformed(evt);
            }
        });

        ShortBreathSymptomBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ShortBreathSymptomBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShortBreathSymptomBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painAndSymptomsLayout = new javax.swing.GroupLayout(painAndSymptoms);
        painAndSymptoms.setLayout(painAndSymptomsLayout);
        painAndSymptomsLayout.setHorizontalGroup(
            painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painAndSymptomsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(breath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(breathInfo))
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(wellbeing)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wellbeingInfo))
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(appetite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(appetiteInfo))
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(drowsiness)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drowsinessInfo))
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(anxiety)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(anxietyInfo))
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(depression)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depressionInfo))
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(nausea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nauseaInfo))
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(tiredness)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tirednessInfo))
                    .addGroup(painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(pain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painInfo))
                    .addComponent(symptoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(severity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painAndSymptomsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PainSymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TirednessSymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NauseaSymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DepressionSymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnxietySymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DrowsinessSymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AppetiteSymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WellbeingSymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShortBreathSymptomBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        painAndSymptomsLayout.setVerticalGroup(
            painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painAndSymptomsLayout.createSequentialGroup()
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(symptoms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(severity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pain)
                    .addComponent(painInfo)
                    .addComponent(PainSymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tirednessInfo)
                        .addComponent(TirednessSymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tiredness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nauseaInfo)
                        .addComponent(NauseaSymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nausea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(depressionInfo)
                        .addComponent(DepressionSymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(depression))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anxietyInfo)
                        .addComponent(AnxietySymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(anxiety))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(drowsinessInfo)
                        .addComponent(DrowsinessSymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(drowsiness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(appetiteInfo)
                        .addComponent(AppetiteSymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(appetite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wellbeing)
                        .addComponent(wellbeingInfo))
                    .addComponent(WellbeingSymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painAndSymptomsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(breath)
                        .addComponent(breathInfo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painAndSymptomsLayout.createSequentialGroup()
                        .addComponent(ShortBreathSymptomBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        submitButton.setText("Submit Pain and Symptom Details");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        messagesPanelD.setBackground(new java.awt.Color(255, 255, 204));

        messagesButtonD.setText("Messages");
        messagesButtonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagesButtonDActionPerformed(evt);
            }
        });

        newMessagesInfoD.setText("There are 0 messages");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout messagesPanelDLayout = new javax.swing.GroupLayout(messagesPanelD);
        messagesPanelD.setLayout(messagesPanelDLayout);
        messagesPanelDLayout.setHorizontalGroup(
            messagesPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesPanelDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messagesPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshButton)
                    .addComponent(messagesButtonD))
                .addGap(18, 18, 18)
                .addComponent(newMessagesInfoD)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        messagesPanelDLayout.setVerticalGroup(
            messagesPanelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messagesPanelDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messagesButtonD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addContainerGap())
            .addGroup(messagesPanelDLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(newMessagesInfoD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emergencyP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(submitButton)
                        .addGap(49, 49, 49))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(painAndSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(212, 212, 212))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(messagesPanelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(databaseP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 412, Short.MAX_VALUE)
                        .addComponent(logOutP)
                        .addGap(63, 63, 63))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(databaseP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logOutP))
                .addGap(25, 25, 25)
                .addComponent(messagesPanelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emergencyP, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(painAndSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(submitButton)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Event Listener for the emergency button
    private void emergencyPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyPActionPerformed
        
        JOptionPane.showMessageDialog(null, "911 has been contacted, Help is on the way!");
    }//GEN-LAST:event_emergencyPActionPerformed

    private void logOutPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutPActionPerformed
        JOptionPane.showMessageDialog(null, "You have succesfully logged out!");
    	new LogInUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logOutPActionPerformed

    private void databasePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databasePActionPerformed
        new PatientDatabseUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_databasePActionPerformed

    private void PainSymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PainSymptomBoxActionPerformed

    }//GEN-LAST:event_PainSymptomBoxActionPerformed

    private void TirednessSymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TirednessSymptomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TirednessSymptomBoxActionPerformed

    private void NauseaSymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NauseaSymptomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NauseaSymptomBoxActionPerformed

    private void wellbeingInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wellbeingInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wellbeingInfoActionPerformed

    private void DepressionSymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepressionSymptomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepressionSymptomBoxActionPerformed

    private void AnxietySymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnxietySymptomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnxietySymptomBoxActionPerformed

    private void DrowsinessSymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrowsinessSymptomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrowsinessSymptomBoxActionPerformed

    private void AppetiteSymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppetiteSymptomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AppetiteSymptomBoxActionPerformed

    private void WellbeingSymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WellbeingSymptomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WellbeingSymptomBoxActionPerformed

    private void ShortBreathSymptomBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortBreathSymptomBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShortBreathSymptomBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
       
        try{
        	String name = User.getName();
            String sql = "Insert into SymptomRatings (name, painlevel, tiredlevel, nausealevel, depressionlevel, anxietylevel, drowsinesslevel, appetitelevel, wellbeinglevel, breathlevel) values (?,?,?,?,?,?,?,?,?,?)";
            Connection conn = sqliteConnection.dbConnector();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, name);
            
            pst.setObject(2, PainSymptomBox.getSelectedItem());
            pst.setObject(3, TirednessSymptomBox.getSelectedItem());
            pst.setObject(4, NauseaSymptomBox.getSelectedItem());
            pst.setObject(5, DepressionSymptomBox.getSelectedItem());
            pst.setObject(6, AnxietySymptomBox.getSelectedItem());
            pst.setObject(7, DrowsinessSymptomBox.getSelectedItem());
            pst.setObject(8, AppetiteSymptomBox.getSelectedItem());
            pst.setObject(9, WellbeingSymptomBox.getSelectedItem());
            pst.setObject(10, ShortBreathSymptomBox.getSelectedItem());
            pst.execute();
            
            //Statement stmt = null;
            //stmt = conn.createStatement();
            //ResultSet re = stmt.executeQuery("Select * From SymptomRatings;");
            
            String sq2 = "select painlevel, tiredlevel, nausealevel, depressionlevel, anxietylevel, drowsinesslevel, appetitelevel, wellbeinglevel, breathlevel from SymptomRatings";
            pst = conn.prepareStatement(sq2);
            re = pst.executeQuery();
            
            if (re.next()){
                int pain = re.getInt("painlevel");
                int tired = re.getInt("tiredlevel");
                int nausea = re.getInt("nausealevel");
                int depression = re.getInt("depressionlevel");
                int anxiety = re.getInt("anxietylevel");
                int drowsiness = re.getInt("drowsinesslevel");
                int appetite = re.getInt("appetitelevel");
                int wellbeing = re.getInt("wellbeinglevel");
                int breath = re.getInt("breathlevel");
                
                User patient = new User();
                
                JOptionPane.showMessageDialog(null, "Symptoms Submitted");
                //JOptionPane.showMessageDialog(null, patient.calcPatientPriority(pain, tired, nausea, depression, anxiety, drowsiness, appetite, wellbeing, breath));
            }
            
            //JOptionPane.showMessageDialog(null, "Symptoms Submitted");
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void messagesButtonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagesButtonDActionPerformed
        new MessagesUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_messagesButtonDActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        try{
            int mCount = 0;
            String recieve = User.getUsername();
            String sql = "SELECT Recieve FROM Messages";
            Connection conn = sqliteConnection.dbConnector();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next())
            {
                String check = rs.getString("Recieve");
                if(check.equals(recieve))
                {
                    mCount++;
                }
            }
            conn.close();
            newMessagesInfoD.setText("There are "+mCount+" messages");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    // Event Listener for the messages button
    private void messageActionPerformed(java.awt.event.ActionEvent evt) {
        new MessagesUI().setVisible(true);
        this.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AnxietySeverity;
    private javax.swing.JComboBox AnxietySymptomBox;
    private javax.swing.ButtonGroup AppetiteSeverity;
    private javax.swing.JComboBox AppetiteSymptomBox;
    private javax.swing.ButtonGroup BreathSeverity;
    private javax.swing.ButtonGroup DepressionSeverity;
    private javax.swing.JComboBox DepressionSymptomBox;
    private javax.swing.ButtonGroup DrowsinessSeverity;
    private javax.swing.JComboBox DrowsinessSymptomBox;
    private javax.swing.ButtonGroup NauseaSeverity;
    private javax.swing.JComboBox NauseaSymptomBox;
    private javax.swing.ButtonGroup PainSeverity;
    private javax.swing.JComboBox PainSymptomBox;
    private javax.swing.JComboBox ShortBreathSymptomBox;
    private javax.swing.ButtonGroup TirednessSeverity;
    private javax.swing.JComboBox TirednessSymptomBox;
    private javax.swing.ButtonGroup WellbeingSeverity;
    private javax.swing.JComboBox WellbeingSymptomBox;
    private javax.swing.JLabel anxiety;
    private javax.swing.JButton anxietyInfo;
    private javax.swing.JLabel appetite;
    private javax.swing.JButton appetiteInfo;
    private javax.swing.JLabel breath;
    private javax.swing.JButton breathInfo;
    private javax.swing.JButton databaseP;
    private javax.swing.JLabel depression;
    private javax.swing.JButton depressionInfo;
    private javax.swing.JLabel drowsiness;
    private javax.swing.JButton drowsinessInfo;
    private javax.swing.JButton emergencyP;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton logOutP;
    private javax.swing.JButton messagesButtonD;
    private javax.swing.JPanel messagesPanelD;
    private javax.swing.JLabel nausea;
    private javax.swing.JButton nauseaInfo;
    private javax.swing.JLabel newMessagesInfoD;
    private javax.swing.JLabel pain;
    private javax.swing.JPanel painAndSymptoms;
    private javax.swing.JButton painInfo;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel severity;
    private javax.swing.JLabel severityLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JPanel symptoms;
    private javax.swing.JLabel symptomsLabel;
    private javax.swing.JLabel tiredness;
    private javax.swing.JButton tirednessInfo;
    private javax.swing.JLabel wellbeing;
    private javax.swing.JButton wellbeingInfo;
    // End of variables declaration//GEN-END:variables
}
